##############################################################
# Google Cloud Engine Deployment Config for a Nuxt application
#
# - See also: https://nuxtjs.org/faq/appengine-deployment
# - Line #18 and #20 have been modified from the original
#   to allow for sw.js file to be uploaded by the that handler
##############################################################

runtime: nodejs10

instance_class: F2

handlers:
  - url: /_nuxt
    static_dir: .nuxt/dist/client
    secure: always

  - url: /(.*\.(gif|png|jpg|ico|txt|js))$
    static_files: static/\1
    upload: static/.*\.(gif|png|jpg|ico|txt|js)$
    secure: always

  - url: /.*
    script: auto
    secure: always

env_variables:
  HOST: '0.0.0.0'
  NODE_ENV: 'production'